### ISSUE TITLE
/home/user/raisim_workspace/raisim_mpc/raisimGymTorch/../libs/osqp/include/glob_opts.h:13:10: fatal error: osqp_configure.h: No such file or directory

### ISSUE THREAD

**Issue by bloom1123** [reeceomahoney/raisim_mpc#1]
when i run python setup.py develop, it appears this problem. how i fix it? Thank you.

**Comment by reeceomahoney** [comment]
Have you altered any of the include paths in the CMakeLists? osqp_configure.h is in the same file as glob_opts so it should be able to find it.

**Comment by reeceomahoney** [comment]
Sorry, actually this file is generated by the CMake in osqp/include. Run this CMake first and see if that works

**Comment by reeceomahoney** [comment]
Sorry correction, this file is generated by the top-level CMake in osqp. In libs/osqp run the following.
```
mkdir build
cd build
cmake ..
```
Then try again. You may have to do this for the other lib folders too, I haven't linked them all together in CMake
